environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.15"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.9"
      PYTHON_ARCH: "64"

matrix:
  fast_finish: true

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "curl -OutFile ctags.zip -Uri https://github.com/universal-ctags/ctags-win32/releases/download/2018-03-13%2F5010e849/ctags-2018-03-13_5010e849-x64.zip"
  - "7z e ctags.zip -o C:\Users\appveyor\bin ctags.exe"
  - "set PATH=%PATH%;C:\Users\appveyor\bin"
  - "%PYTHON%/python.exe -m pip install --upgrade pip setuptools"
  - "%PYTHON%/python.exe -m pip install .[all] .[test]"

test_script:
  - "%PYTHON%/Scripts/pytest.exe test/"

build: false  # Not a C# project

cache:
  - '%APPDATA%\pip\Cache'
